<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Bean;

use generateur_cv\Model\Bean\Generated\FormationBaseBean;

/**
 * The FormationBean class maps the 'formation' table in database.
 */
class FormationBean extends FormationBaseBean
{

    /**
     * The setter for the "start_date" column.
     *
     * @param \DateTimeInterface $start_date
     */
    public function setStartDate(\DateTimeInterface $start_date = null)
    {
        $this->set('start_date', $start_date, 'formation');
    }



    /**
     * The setter for the "end_date" column.
     *
     * @param \DateTimeInterface $end_date
     */
    public function setEndDate(\DateTimeInterface $end_date = null)
    {
        $this->set('end_date', $end_date, 'formation');
    }


}
