<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Bean;

use generateur_cv\Model\Bean\Generated\FormationBaseBean;

/**
 * The FormationBean class maps the 'formation' table in database.
 */
class FormationBean extends FormationBaseBean
{
}
