<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Bean;

use generateur_cv\Model\Bean\Generated\KnowledgeBaseBean;

/**
 * The KnowledgeBean class maps the 'knowledge' table in database.
 */
class KnowledgeBean extends KnowledgeBaseBean
{
}
