<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Bean;

use generateur_cv\Model\Bean\Generated\KnowledgeBaseBean;

/**
 * The KnowledgeBean class maps the 'knowledge' table in database.
 */
class KnowledgeBean extends KnowledgeBaseBean
{

    /**
     * The setter for the "start_date" column.
     *
     * @param \DateTimeInterface $start_date
     */
    public function setStartDate(\DateTimeInterface $start_date = null)
    {
        $this->set('start_date', $start_date, 'knowledge');
    }

    /**
     * The setter for the "end_date" column.
     *
     * @param \DateTimeInterface $end_date
     */
    public function setEndDate(\DateTimeInterface $end_date = null)
    {
        $this->set('end_date', $end_date, 'knowledge');
    }
}
