<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Bean;

use generateur_cv\Model\Bean\Generated\SkillBaseBean;

/**
 * The SkillBean class maps the 'skill' table in database.
 */
class SkillBean extends SkillBaseBean
{
}
