<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not put any code except 'define' operations
 * as it could be overwritten.
 * Instead, use the Mouf User Interface to set all your constants: http://[server]/generateur_cv/vendor/mouf/mouf/mouf/config
 */

/**
 * Set to true to enable debug/development mode.
 */
define('DEBUG', true);
/**
 * A random string. It should be different for any application deployed.
 */
define('SECRET', 'KeMcrysdSzRdoJ4pQ1Hw');
/**
 * The database host (the IP address or URL of the database server).
 */
define('DB_HOST', 'localhost');
/**
 * The database port (the port of the database server, keep empty to use default port).
 */
define('DB_PORT', '');
/**
 * The name of your database.
 */
define('DB_NAME', 'cv');
/**
 * The username to access the database.
 */
define('DB_USERNAME', 'root');
/**
 * The password to access the database.
 */
define('DB_PASSWORD', '');
