<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Dao;

use generateur_cv\Model\Dao\Generated\FormationBaseDao;

/**
 * The FormationDao class will maintain the persistence of FormationBean class into the formation table.
 */
class FormationDao extends FormationBaseDao
{
    /**
     * return formation data for last inserted user
     * @param int $id
     * @return array
     */
    public function getFormationUser($id){
        $link = mysqli_connect("localhost","root","","cv") or die($link);
        $sql = mysqli_query($link,'SELECT * FROM formation WHERE user = '.$id);
        $return = mysqli_fetch_all($sql,MYSQLI_ASSOC);
        return $return;
    }
}
