<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Dao;

use generateur_cv\Model\Dao\Generated\FormationBaseDao;

/**
 * The FormationDao class will maintain the persistence of FormationBean class into the formation table.
 */
class FormationDao extends FormationBaseDao
{

}
