<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Dao;

use generateur_cv\Model\Dao\Generated\KnowledgeBaseDao;

/**
 * The KnowledgeDao class will maintain the persistence of KnowledgeBean class into the knowledge table.
 */
class KnowledgeDao extends KnowledgeBaseDao
{

}
