<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Dao;

use generateur_cv\Model\Dao\Generated\KnowledgeBaseDao;

/**
 * The KnowledgeDao class will maintain the persistence of KnowledgeBean class into the knowledge table.
 */
class KnowledgeDao extends KnowledgeBaseDao
{
    /**
     * return knowledge data for last inserted user
     * @param int $id
     * @return array
     */
    public function getKnowledgeUser($id){
        $link = mysqli_connect("localhost","root","","cv") or die($link);
        $sql = mysqli_query($link,'SELECT * FROM knowledge WHERE user = '.$id);
        $return = mysqli_fetch_all($sql,MYSQLI_ASSOC);
        return $return;
    }
}
