<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace generateur_cv\Model\Dao;

use generateur_cv\Model\Dao\Generated\SkillBaseDao;

/**
 * The SkillDao class will maintain the persistence of SkillBean class into the skill table.
 */
class SkillDao extends SkillBaseDao
{

}
